# Generated by Django 4.0.3 on 2022-03-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Name', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('Author', models.CharField(max_length=64)),
                ('Synopsis', models.CharField(max_length=300)),
                ('Uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Uploadedby', to='kijita.person')),
            ],
        ),
    ]
